# Ne jamais modifier ici
apiVersion: skyline.local/v1
# Ne jamais modifier ici
kind: CTFChallenge
metadata:
    name: gate-bypass-enzo
    # Ne jamais modifier ici
    namespace: ctfd
spec:
    name: Gate Bypass
    description: |
        Le nouveau système de sécurité de SKL Corp utilise une porte d'accès protégée par un login/mot de passe. Cependant, un employé mécontent a laissé entendre que la base de données était mal configurée... Parviendras-tu à contourner l'authentification pour récupérer le flag caché dans le panneau d'administration ?
    category: Web
    points: 100
    type: standard
    state: visible
    instance: true
    connection_info: Lancer votre instance sur http://deployer.ctfd.tail575cd.ts.net
    max_attempts: 0
    image: ghcr.io/sp00kyskelet0n/skylinectf-challenges/gate-bypass:latest
    port: 80
    creator: Enzo
    flag: ENC[AES256_GCM,data:hztxvHf4vmo9tOBLnTm5828D,iv:Oq1E4v4FegykbFllpG3emSY1NsWrR8EBunEDgN17rb0=,tag:XlwlNkIuejv5GEz9m/482A==,type:str]
sops:
    lastmodified: "2026-02-06T08:58:07Z"
    mac: ENC[AES256_GCM,data:ac2QgP5OKKX/rVTGeMrUINs8iZODfi9omCKzekQKTuXj+e/YELVcVSuN8ZQtcahc0dIPSPdBFM5Yym0/t1Um+Hj7miOVfiGCzmyC/o3Ge/2P56XuKDvD4ttFdWnHj0f1SVWEpEPVSJLAzXYxfM8vnVzzDw/fKQxkU3eIIJxuK2U=,iv:etZtUwWtzRO19hcuCOEwo7AHfUun4wyfWlkSb6tSbVM=,tag:nsnr3SyHD+IEZqG63Q/UVw==,type:str]
    pgp:
        - created_at: "2026-02-06T08:58:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4Wg+3KzyZPEAQ/9EXm9UlI+Z9VYOJ/M0U5hY2KXiMDAJyqRPLqW8DM1fIEk
            gWelCGZ4RjefzDZyTuou6k6pwNsu2d4TTPWZzxeS84pD8DT4Th8vuNxu5Fen8NSG
            qC6P2F1DvT0J96JUKNunNxJQ9dhkgZ4rqVPi8M7AcDPJKOK+JemmiHrVkhXY1lgy
            jlPcx3LHUsUupkDJBMD/LKc+cDF7Q61hQnY9IHLqdBAFTN5GfOK7V7Z/d/WHj5HH
            D6Wu3N/lbOjMnA73J/8q36wrjq/Mua1l241S2oY5TWaaokiuPXNn0r6emvOrem6f
            IRvEFufWe7QT6ZdJv+4tso5vBXiqFjbDSKgz21zEvp2BdS93S/Db6eANilCKspDR
            kxeFpysIAI/VYgAxqMahyCejMlNPwkC/bjhX8gnncdSnMmjlN1abfSBeGauxwsmG
            rFuLsx27lSvnqe4NDQZZ/Nx+VPMf4kaJrtObpNmcSF+W232XKEIhSsUET1PF7uq1
            enSEiXoL8GhRhP4Lqxz+f0WXUVF17+IA41WoFu4vXNvlN03ImcatAw5Uj/4aYHti
            djr0uufB4pM852jts9RaB2CDSLzR8sSXvLzgCzOqgy56j0bDFRc+s0PmgupspQ2u
            Rq5ePIgB90rYho20F/qr3TLgePARmZZkpz3U7xFcj5WmsEejUl1l+N3K53pSQcLU
            aAEJAhAi9FHOjg83eaMu5mF8pxNT89g1ZL0hzQAIuW1cPbsJcnHSJOPrFNhzQp5i
            sGFTMA0t9DHgGX7lIHNgnyXfrkfqo+MU4QoBhplVdqB1BP4RlbDh/3GOpnus/dxO
            /XLXiXp9N9Kj
            =4zJh
            -----END PGP MESSAGE-----
          fp: 2F678007F08254265530095FB5B68F8BCE0CB069
    encrypted_regex: ^(data|stringData|flag|password|secret)$
    version: 3.11.0
