apiVersion: skyline.local/v1
kind: CTFChallenge
metadata:
    name: paradox-machine
    namespace: ctfd
spec:
    name: Paradox Machine
    description: |
        La Paradox Machine est le simulateur temporel le plus puissant jamais construit.
        Les opérateurs y entrent des coordonnées spatio-temporelles pour simuler les paradoxes potentiels avant chaque saut.
        Un compte opérateur de test est disponible (operator/operator).
        Le moteur de simulation semble traiter vos entrées d'une manière particulière...
        Certains disent que la machine est plus puissante qu'on ne le pense.
        Un fichier confidentiel contenant des coordonnées critiques serait stocké quelque part sur le serveur.
    category: Web
    type: dynamic
    initial: 500
    decay: 6
    minimum: 125
    image: ghcr.io/sp00kyskelet0n/skylinectf-challenges/paradox-machine:latest
    port: 8000
    instance: true
    creator: Enzo QUELENIS
    flag: ENC[AES256_GCM,data:L9QS83Xb74V42EKe4pLU5lQ42tQWEaXtL6qbs0BpibvmIYLLRg==,iv:UuscqB5JyG7MRUDmaW/EFthNfPgT9HCKzMrm3Uw6ibU=,tag:mhBrfyMZHzJSi+FJNXufhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-04-01T09:28:24Z"
    mac: ENC[AES256_GCM,data:EW24kORPX0UOiMZXC7qIQ9X8Q/eYlwhDs2r57z0mpWbNM1Np6vzqzfNVlveiWEkvNUAZijxZU+1209SAW4nVweH1FScNxzfe2UwfjdTSULTIZgDRattXVLD0NaSBOdVwHBNfGDE76zS3xl+LOYXS2lYOSEtJatcsVaoBoNi2FbI=,iv:MmGPeKCxvoywvtRKYdVOtTCdezgltWQGJ5ImC2UdwyY=,tag:892zvUO007hxkTiYFW9aJw==,type:str]
    pgp:
        - created_at: "2026-04-01T09:28:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4Wg+3KzyZPEAQ//W9h8XxwozhASALy72xAPo+rapdQ3lJ6YbUh/efHbG+gp
            JNy9uonPwjLQbzXNs0Uq9d2YKDOPvXb8beOOUOVLzkqztZoyPyJWVL6LtL1YGeTj
            eJjyO2aa8ZADxKuC0pQqCpmlMpiDsWxUt1w8ON76K/T3tEiCdy6M53lAdVQw9Hwn
            v/QGzhIbmQO0KbxPdh3wQWymKGcMHeids+4GS4Z0RxJKiJ1Bqgy+LM3R0P5kUFva
            qLnzdi1QCHARgZ1DN5+1WRQlcaw6GchMdZ7iy7oC93w1guDWClflmRAgr07KSXg/
            EGjULFgY4rqU5U1GtHFI2d8oDf6hQy3NXvtlocZAF81KklmY+VRtSYuxGqBh93YM
            CECsS2sXKpKozcWDMfm97p7kl5JXL1x4obo4RSrt9DcIeotCkOEWWy+WkgZXAYUe
            MQVa+zxJ5V4NF2X2uXcni8EQ4/L9mWVmEmDUzYBD+0n3+jaXuFMbbNRPZTO9hjXh
            J4UJBLGaNw3VGqrefPjQ9J1sAtZzZGBGlwpzPiuuFH+BQ1BAEQr8V02Ualw1AWF/
            UmECI9DNPyZSVJHrAzdc5pn5h362ic67VunAaJiOYK88EcIupy0mLoZago9utRZ7
            je2KRnMdJj+viytVwaxtNHQrwgQOP8JDfFqd9T/FzGXe86pvRAMgDDS3NFkJEBHS
            XgHymdu7+2XDWmLC2D/t8khZoJX3I213QNY663ZSbxfQtnwp+E5TPNwedIdnYHbq
            syCNtjHNOgYhm/4h3z+MRZWXyalBH7JZ3hrtJ2qYO9GbeKe+1FJZdveHduX+7fM=
            =VYhp
            -----END PGP MESSAGE-----
          fp: 2F678007F08254265530095FB5B68F8BCE0CB069
    encrypted_regex: ^(data|stringData|flag|password|secret)$
    version: 3.8.1
